## If you're looking for the deny.toml template, head over to
## https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
[graph]
targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "aarch64-unknown-linux-gnu" },
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "aarch64-apple-darwin" },
	{ triple = "x86_64-apple-darwin" },
	{ triple = "x86_64-pc-windows-msvc" },
]

[advisories]
version = 2
ignore = []

[bans]
multiple-versions = "deny"
deny = []
skip = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
	"Apache-2.0",
	# "Apache-2.0 WITH LLVM-exception",
	"MIT",
	# "MPL-2.0",
]
